---
- hosts: localhost
  vars files:
    - host_vars/config_vars.yaml
  gather_facts: true
  
  roles:
    - role: openstack-common
# - role: openstack-images
    - role: create-volume
    - role:create-security-group
    - role: create-instance


- hosts: all
  vars files:
    - host_vars/config_vars.yaml
  gather facts: true
  vars:
    - ansible_user: ubuntu
    - ansible ssh private key file: ~/.ssh/ccc-group17.pem
    - ansible ssh common args: '-o StrictHostKeyChecking=no"

  roles:
    - role: config-instance
    - role: setup-couchdb