# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: couchdb-demo
instance_flavor: uom.mse.1c4g

# Volume 
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 10
    # device: /dev/vdb
    # mountpoint: /home/ubuntu/COMP90024
  - vol_name: demo-vol-1-2
    vol_size: 10
  #   device: /dev/vdb
  #   mountpoint: /data
  # - vol_name: instance3-volume
  #   vol_size: 10
  #   device: /dev/vdb
  #   mountpoint: /data
  # - vol_name: instance4-volume
  #   vol_size: 10
  #   device: /dev/vdb
  #   mountpoint: /data

# Create a TCP rule covering all ports,security_groups
security_groups:
  - name: demo_ssh
    description: "security group for demo_ssh"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "security group for demo_http"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  # - name: instance3-security-group
  #   description: "security group for instance3 server"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0
  # - name: instance4-security-group
  #   description: "security group for instance4 server"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0



# Instance 
instances:
  - name: instance1
    security_groups: instance1-security-group
    volume_ids: '{ instance1_volumes|default([]) }'
    volumes: ['instance1-volume']
  - name: instance2
    security_groups: instance2-security-group
    volume_ids: '{ instance2_volumes|default([]) }'
    volumes: ['instance2-volume']
  # - name: instance3
  #   security_groups: instance3-security-group
  #   volume_ids: '{ instance3_volumes|default([]) }'
  #   volumes: ['instance3-volume']
  # - name: instance4
  #   security_groups: instance4-security-group
  #   volume_ids: '{ instance4_volumes|default([]) }'
  #   volumes: ['instance4-volume']