---
#Create a security group
- name: Creat a security group
  openstack.cloud.security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups}}'


- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: '{{sg_names|default([]) + [ item.name ]}}'
  loop: '{{ security_groups }}'

- ansible.builtin.debug:
    msg: "Secruity groups {{ sg_names}} have been creat ed."

# create sg rules
- name: Create security group rules
  openstack.cloud.security_group_rules:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{item.port_range_min }}'
    port_range_max: '{{item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_groups}}'