- hosts: deploy_node
  vars_files:
    - variables/frontend_backend_vars.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: couchdb-demo.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: deploy_web_service
  