---
- name: Install packages for web app
  hosts: all
  become: true

  tasks:
  - name: Install required packages using apt
    apt:
      name: 
        - python3
        - python3-pip
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-setuptools
        - mongodb-org
      state: latest
      update_cache: yes

  - name: Install Django and Django Rest Framework using pip
    pip:
      name:
        - Django
        - djangorestframework
        - markdown
        - django-filter
      state: latest
